import { Link } from "react-router-dom";
import { ArrowRight, Bot, FlaskConical, ShieldCheck } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SEO from "@/components/SEO";

export default function SeoTools() {
  return <div className="min-h-screen bg-white text-slate-950"><SEO title="Herramientas SEO gratuitas | Ferova" description="Herramientas especializadas para evaluar fundamentos técnicos, contenido, autoridad y preparación de una marca para AI Search." path="/recursos/herramientas" lang="es" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Recursos", path: "/recursos" }, { name: "Herramientas", path: "/recursos/herramientas" }]} /><Header lang="es" /><main className="pt-20">
    <section className="bg-[#541014] py-20 text-white md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><FlaskConical className="h-9 w-9 text-[#e0bd52]" /><h1 className="mt-6 max-w-4xl font-display text-4xl font-bold tracking-tight md:text-6xl">Herramientas para revisar señales SEO, no para fabricar certezas.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Cada resultado es orientativo y explica sus límites. Las mediciones reales requieren fuentes, consultas, fechas de corte y una metodología definida.</p></div></section>
    <section className="py-20 md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><article className="grid gap-10 rounded-3xl border border-slate-200 p-8 md:grid-cols-[1fr_.65fr] md:items-center md:p-12"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#f4eadb] px-3 py-1 text-xs font-bold uppercase tracking-wider text-[#6a4c30]"><Bot className="h-4 w-4" /> AI Search</span><h2 className="mt-6 font-display text-3xl font-bold md:text-5xl">Evaluador de preparación para AI Search</h2><p className="mt-5 max-w-2xl leading-7 text-slate-600">Revisa cinco bases relacionadas con datos estructurados, contenido, presencia externa, respuestas directas y conocimiento de menciones actuales.</p><Link to="/recursos/herramientas/evaluador-preparacion-ai-search" className="seo-primary-button mt-8">Abrir evaluador <ArrowRight className="h-4 w-4" /></Link></div><aside className="rounded-2xl bg-slate-50 p-6"><ShieldCheck className="h-7 w-7 text-[#8c6905]" /><h3 className="mt-5 font-display text-xl font-bold">Qué no hace</h3><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600"><li>No consulta plataformas de IA.</li><li>No mide menciones reales.</li><li>No garantiza apariciones.</li><li>No sustituye una auditoría.</li></ul></aside></article></div></section>
    <section className="bg-slate-50 py-20 text-center"><div className="container mx-auto px-4 md:px-6"><h2 className="font-display text-3xl font-bold md:text-4xl">¿Necesitas una medición con competidores y consultas reales?</h2><Link to="/contacto" className="mt-7 inline-flex items-center gap-2 font-semibold text-[#6a4c30]">Solicitar precio y alcance <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer lang="es" /></div>;
}
