import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, CalendarClock, CheckCircle2, ShoppingBag } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SEO from "@/components/SEO";
import { trackEvent } from "@/lib/analytics";

const cases = [
  { id: "ecommerce-cableado-estructurado", sector: "Tecnología B2B", service: "SEO técnico", icon: BarChart3, title: "Arquitectura e indexación para un ecommerce de cableado estructurado", problem: "Un catálogo extenso, búsquedas por número de parte y errores acumulados dificultaban que Google encontrara y priorizara las páginas correctas.", period: "Trabajo continuo; fechas y métricas pendientes de validación documental." },
  { id: "ecommerce-mascotas", sector: "Mascotas", service: "SEO ecommerce", icon: ShoppingBag, title: "Recuperación técnica y orgánica de un ecommerce de mascotas", problem: "La inestabilidad técnica y una pérdida comercial significativa exigían ordenar la plataforma antes de escalar el trabajo orgánico.", period: "Resultados relativos en revisión; no se publican valores comerciales confidenciales." },
];

export default function SeoCases() {
  const [filter, setFilter] = useState("Todos");
  const filters = ["Todos", ...Array.from(new Set(cases.map((c) => c.service)))];
  const visible = filter === "Todos" ? cases : cases.filter((c) => c.service === filter);
  return <div className="min-h-screen bg-white text-slate-950"><SEO title="Casos de éxito SEO para ecommerce | Evidencia y metodología" description="Casos SEO para ecommerce con contexto, intervención y evidencia. Las métricas se publican únicamente después de validar fuente, periodo y autorización." path="/casos-de-exito" lang="es" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Casos de éxito", path: "/casos-de-exito" }]} /><Header lang="es" /><main className="pt-20">
    <section className="bg-[#071a2f] py-20 text-white md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">Casos de éxito</p><h1 className="mt-5 max-w-4xl font-display text-4xl font-bold tracking-tight md:text-6xl">Evidencia antes que titulares.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Cada caso debe explicar el contexto, el diagnóstico, la intervención y sus limitaciones. Las cifras solo se publican con fecha, fuente, definición y permiso.</p></div></section>
    <section className="border-b border-slate-200 bg-slate-50 py-8"><div className="container mx-auto flex max-w-6xl flex-wrap gap-3 px-4 md:px-6">{filters.map((f) => <button type="button" key={f} onClick={() => { setFilter(f); trackEvent("case_filter_used", { filter: f, language: "es" }); }} className={`rounded-full px-5 py-2 text-sm font-semibold transition ${filter === f ? "bg-blue-700 text-white" : "border border-slate-300 bg-white text-slate-700 hover:border-blue-400"}`}>{f}</button>)}</div></section>
    <section className="py-20 md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><div className="grid gap-6 md:grid-cols-2">{visible.map((c) => { const Icon = c.icon; return <article key={c.id} className="flex h-full flex-col rounded-2xl border border-slate-200 p-7"><div className="flex items-center justify-between"><span className="rounded-xl bg-blue-50 p-3 text-blue-700"><Icon className="h-6 w-6" /></span><span className="rounded-full border border-slate-200 px-3 py-1 text-xs text-slate-600">{c.service}</span></div><p className="mt-7 text-sm font-semibold text-blue-700">{c.sector}</p><h2 className="mt-2 font-display text-2xl font-bold">{c.title}</h2><p className="mt-4 flex-1 leading-7 text-slate-600">{c.problem}</p><div className="mt-6 flex gap-3 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950"><CalendarClock className="mt-0.5 h-5 w-5 shrink-0" /><span>{c.period}</span></div><Link to={`/casos-de-exito/${c.id}`} className="mt-7 inline-flex items-center gap-2 font-semibold text-blue-700">Ver narrativa del caso <ArrowRight className="h-4 w-4" /></Link></article>; })}</div></div></section>
    <section className="bg-slate-50 py-20"><div className="container mx-auto grid max-w-6xl gap-12 px-4 md:px-6 lg:grid-cols-2"><div><p className="seo-kicker">Estándar de evidencia</p><h2 className="mt-4 font-display text-3xl font-bold md:text-5xl">Qué debe acompañar una métrica pública.</h2></div><ul className="space-y-4">{["Fecha de corte y periodo comparado.","Fuente, unidad y definición de la métrica.","Baseline y fórmula de comparación.","Autorización y nota de limitaciones."].map((x) => <li key={x} className="flex gap-3 rounded-xl bg-white p-5 shadow-sm"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-teal-600" />{x}</li>)}</ul></div></section>
    <section className="py-20 text-center"><div className="container mx-auto px-4 md:px-6"><h2 className="mx-auto max-w-3xl font-display text-3xl font-bold md:text-5xl">Tu proyecto no necesita parecerse a otro para poder evaluarse con rigor.</h2><Link to="/contacto" className="seo-primary-button mt-9">Evaluar mi proyecto <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer lang="es" /></div>;
}
