import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, ClipboardCheck, FileSearch, LineChart, ListChecks, MessagesSquare, Wrench } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SEO from "@/components/SEO";

const phases = [
  { icon: MessagesSquare, title: "Contexto", text: "Objetivo, modelo de negocio, tecnología, mercado, historial y capacidad del equipo." },
  { icon: FileSearch, title: "Diagnóstico", text: "Evidencia técnica, de búsqueda y negocio para separar causas, síntomas y supuestos." },
  { icon: ListChecks, title: "Priorización", text: "Decisiones ordenadas por impacto, esfuerzo, dependencia, riesgo y velocidad de aprendizaje." },
  { icon: Wrench, title: "Ejecución", text: "Responsables, criterios de aceptación y acompañamiento para convertir recomendaciones en cambios." },
  { icon: ClipboardCheck, title: "Validación", text: "Revisión técnica de implementaciones y registro de qué se publicó, cuándo y con qué alcance." },
  { icon: LineChart, title: "Medición", text: "Indicadores, fechas de corte y aprendizajes para decidir el siguiente ciclo sin borrar la historia." },
];

export default function SeoMethod() {
  return <div className="min-h-screen bg-white text-slate-950"><SEO title="Método Ferova aplicado a SEO: diagnosticar, priorizar y ejecutar" description="Así se aplica el método Ferova a proyectos SEO complejos: contexto, diagnóstico, priorización, ejecución, validación y medición trazable." path="/metodo-ferova" lang="es" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Método Ferova", path: "/metodo-ferova" }]} /><Header lang="es" /><main className="pt-20">
    <section className="relative overflow-hidden bg-[#071a2f] py-20 text-white md:py-28"><div className="absolute left-1/2 top-0 h-80 w-80 -translate-x-1/2 rounded-full bg-blue-600/20 blur-3xl" /><div className="container relative mx-auto max-w-6xl px-4 text-center md:px-6"><p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">Método Ferova aplicado a SEO</p><h1 className="mx-auto mt-5 max-w-5xl font-display text-4xl font-bold tracking-tight md:text-6xl">Diagnosticar antes de ejecutar. Medir sin borrar la historia.</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-300">Un proceso para convertir problemas SEO complejos en decisiones claras, trabajo verificable y aprendizaje acumulado.</p></div></section>
    <section className="py-20 md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><p className="seo-kicker">El proceso</p><h2 className="mt-4 max-w-3xl font-display text-3xl font-bold md:text-5xl">Seis fases conectadas, con evidencia y criterios de salida.</h2><ol className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{phases.map(({ icon: Icon, title, text }, i) => <li key={title} className="rounded-2xl border border-slate-200 p-7"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-blue-700" /><span className="font-mono text-sm text-slate-400">0{i + 1}</span></div><h3 className="mt-8 font-display text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></li>)}</ol></div></section>
    <section className="bg-slate-50 py-20 md:py-24"><div className="container mx-auto grid max-w-6xl gap-12 px-4 md:px-6 lg:grid-cols-2"><div><p className="seo-kicker">Qué recibes</p><h2 className="mt-4 font-display text-3xl font-bold md:text-5xl">Un sistema que tu equipo puede entender y continuar.</h2></div><ul className="space-y-4">{["Diagnóstico que distingue hallazgos, hipótesis y evidencia.","Roadmap con responsables, dependencias y criterios de aceptación.","Registro de decisiones para evitar repetir discusiones ya resueltas.","Medición con baseline, periodo, fuente y limitaciones explícitas."].map((x) => <li key={x} className="flex gap-3 rounded-xl bg-white p-5 shadow-sm"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-teal-600" />{x}</li>)}</ul></div></section>
    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-5xl gap-6 px-4 md:grid-cols-2 md:px-6"><article className="rounded-2xl border border-slate-200 p-8"><p className="seo-kicker">Cómo priorizamos</p><h2 className="mt-4 font-display text-2xl font-bold">Impacto, esfuerzo, dependencia y riesgo.</h2><p className="mt-4 leading-7 text-slate-600">Una recomendación urgente puede ser inútil si depende de otra decisión. El orden del trabajo debe reflejar la realidad técnica y operativa.</p></article><article className="rounded-2xl bg-[#071a2f] p-8 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Cómo medimos</p><h2 className="mt-4 font-display text-2xl font-bold">Baseline, periodo, fuente y definición.</h2><p className="mt-4 leading-7 text-slate-300">No se mezclan ventanas temporales ni se sustituyen cifras históricas. Las correcciones y nuevas observaciones deben quedar fechadas.</p></article></div></section>
    <section className="bg-[#071a2f] py-20 text-center text-white"><div className="container mx-auto px-4 md:px-6"><h2 className="mx-auto max-w-3xl font-display text-3xl font-bold md:text-5xl">Apliquemos el método al problema que tiene tu equipo hoy.</h2><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/contacto" className="seo-primary-button">Evaluar mi proyecto <ArrowRight className="h-4 w-4" /></Link><Link to="/soluciones" className="seo-secondary-button">Ver soluciones</Link></div></div></section>
  </main><Footer lang="es" /></div>;
}
