import { Link } from "react-router-dom";
import { ArrowRight, Check, Compass, FileSearch, MessagesSquare, ShieldCheck } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SEO from "@/components/SEO";
import { trackEvent } from "@/lib/analytics";

const modalities = [
  { id: "session", icon: MessagesSquare, title: "Sesión de dirección SEO", price: "USD 150", note: "60 minutos · pago único", text: "Para revisar una decisión concreta, desbloquear al equipo o validar un enfoque antes de ejecutarlo.", items: ["Contexto previo por formulario", "Sesión de trabajo directa", "Conclusiones y próximos pasos", "Sin promesas de resultado"] },
  { id: "audit", icon: FileSearch, title: "Auditoría SEO técnica", price: "Desde USD 450", note: "Alcance según plataforma y tamaño", text: "Para localizar bloqueos y convertir hallazgos técnicos en un roadmap defendible.", items: ["Rastreo e indexación", "Arquitectura y enlazado", "Priorización por impacto y riesgo", "Presentación de hallazgos"] },
  { id: "advisory", icon: Compass, title: "Acompañamiento SEO senior", price: "Desde USD 1.000/mes", note: "Cupos y alcance limitados", text: "Para equipos o agencias que necesitan dirección continua, QA y apoyo en decisiones complejas.", items: ["Dirección estratégica", "Revisión de backlog", "QA de implementaciones", "Seguimiento y medición"] },
];

export default function SeoPricing() {
  return <div className="min-h-screen bg-white text-slate-950"><SEO title="Precios de consultoría SEO senior en USD | Ferova" description="Modalidades de consultoría SEO senior: sesión de dirección, auditoría técnica y acompañamiento para ecommerce y agencias. Valores en USD." path="/precios" lang="es" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Precios", path: "/precios" }]} /><Header lang="es" /><main className="pt-20">
    <section className="bg-[#071a2f] py-20 text-white md:py-28"><div className="container mx-auto max-w-6xl px-4 text-center md:px-6"><p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">Modalidades en USD</p><h1 className="mx-auto mt-5 max-w-4xl font-display text-4xl font-bold tracking-tight md:text-6xl">Elige el nivel de intervención que necesita tu equipo.</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-300">Los valores orientan la conversación inicial. El alcance final depende de la plataforma, el tamaño del catálogo, la evidencia disponible y la capacidad de implementación.</p></div></section>
    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-6xl gap-6 px-4 md:px-6 lg:grid-cols-3">{modalities.map(({ id, icon: Icon, title, price, note, text, items }, index) => <article key={id} className={`flex flex-col rounded-2xl p-7 ${index === 1 ? "border-2 border-blue-600 shadow-xl shadow-blue-100" : "border border-slate-200"}`}><Icon className="h-7 w-7 text-blue-700" /><h2 className="mt-7 font-display text-2xl font-bold">{title}</h2><p className="mt-5 font-display text-3xl font-bold text-blue-700">{price}</p><p className="mt-1 text-xs text-slate-500">{note}</p><p className="mt-5 leading-7 text-slate-600">{text}</p><ul className="mt-6 flex-1 space-y-3">{items.map((item) => <li key={item} className="flex gap-2 text-sm text-slate-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-teal-600" />{item}</li>)}</ul><Link to={`/contacto?modalidad=${id}`} onClick={() => trackEvent("pricing_card_clicked", { tier: id, lang: "es" })} className="seo-primary-button mt-8">Evaluar alcance <ArrowRight className="h-4 w-4" /></Link></article>)}</div></section>
    <section className="bg-slate-50 py-20"><div className="container mx-auto grid max-w-5xl gap-8 px-4 md:grid-cols-[auto_1fr] md:items-start md:px-6"><ShieldCheck className="h-10 w-10 text-teal-600" /><div><h2 className="font-display text-3xl font-bold">Lo que ningún precio compra</h2><p className="mt-4 leading-7 text-slate-600">No se venden posiciones, tráfico garantizado ni menciones en motores de IA. La consultoría entrega análisis, criterio, acompañamiento y un sistema de medición proporcional al alcance contratado.</p></div></div></section>
    <section className="py-20 text-center"><div className="container mx-auto px-4 md:px-6"><h2 className="mx-auto max-w-3xl font-display text-3xl font-bold md:text-5xl">Si el alcance no está claro, empecemos por el problema.</h2><Link to="/contacto" className="seo-primary-button mt-9">Evaluar mi proyecto <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer lang="es" /></div>;
}
