import { Link } from "react-router-dom";
import { ArrowRight, Blocks, Bot, GitBranch, SearchX, Store, Users } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import SEO from "@/components/SEO";
import { trackEvent } from "@/lib/analytics";

const problems = [
  { key: "crecimiento", icon: Store, title: "El ecommerce no crece orgánicamente", text: "Hay contenido y optimizaciones, pero no una arquitectura ni una priorización conectadas con el catálogo y la demanda.", href: "/servicios/seo-ecommerce", cta: "Revisar SEO ecommerce" },
  { key: "indexacion", icon: SearchX, title: "Google rastrea o indexa lo incorrecto", text: "Facetas, duplicados, JavaScript, canonicals o enlaces internos están consumiendo señales y presupuesto de rastreo.", href: "/auditoria-seo-tecnica", cta: "Evaluar la base técnica" },
  { key: "migracion", icon: GitBranch, title: "Se aproxima una migración o rediseño", text: "El cambio de plataforma, dominio o arquitectura puede perder URLs, enlaces y señales si SEO entra demasiado tarde.", href: "/migraciones-seo", cta: "Controlar el riesgo" },
  { key: "equipo", icon: Users, title: "El equipo necesita dirección SEO senior", text: "Hay capacidad de ejecución, pero falta criterio especializado para decidir, desbloquear o validar trabajo complejo.", href: "/seo-para-agencias", cta: "Ver apoyo para equipos" },
  { key: "arquitectura", icon: Blocks, title: "La arquitectura ya no representa el negocio", text: "Categorías, productos y contenidos compiten entre sí o no cubren cómo busca y compra el mercado.", href: "/servicios/seo-ecommerce", cta: "Ordenar la arquitectura" },
  { key: "ai-search", icon: Bot, title: "No sabemos si estamos preparados para AI Search", text: "Faltan criterios para evaluar entidades, contenido, datos estructurados, autoridad externa y medición de menciones.", href: "/recursos/herramientas/evaluador-preparacion-ai-search", cta: "Hacer autoevaluación" },
];

export default function SeoSolutions() {
  return <div className="min-h-screen bg-white text-slate-950"><SEO title="Soluciones SEO para problemas complejos de ecommerce | Ferova" description="Identifica el problema SEO detrás del estancamiento: indexación, arquitectura, migraciones, capacidad del equipo o preparación para AI Search." path="/soluciones" lang="es" breadcrumbs={[{ name: "Inicio", path: "/" }, { name: "Soluciones", path: "/soluciones" }]} /><Header lang="es" /><main className="pt-20">
    <section className="bg-[#071a2f] py-20 text-white md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">Soluciones por problema SEO</p><h1 className="mt-5 max-w-4xl font-display text-4xl font-bold tracking-tight md:text-6xl">¿Qué está impidiendo que tu sistema orgánico avance?</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">No empezamos por vender una lista de tareas. Empezamos por localizar el problema, entender sus dependencias y elegir la intervención adecuada.</p></div></section>
    <section className="py-20 md:py-28"><div className="container mx-auto max-w-6xl px-4 md:px-6"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{problems.map(({ key, icon: Icon, title, text, href, cta }) => <Link key={key} to={href} onClick={() => trackEvent("problem_selected", { source: "seo_solutions", problem: key, language: "es" })} className="group rounded-2xl border border-slate-200 p-7 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-xl"><Icon className="h-7 w-7 text-blue-700" /><h2 className="mt-7 font-display text-xl font-bold">{title}</h2><p className="mt-3 min-h-[84px] text-sm leading-7 text-slate-600">{text}</p><span className="mt-6 inline-flex items-center gap-2 font-semibold text-blue-700">{cta}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>
    <section className="bg-slate-50 py-20"><div className="container mx-auto grid max-w-5xl gap-10 px-4 md:px-6 lg:grid-cols-2 lg:items-center"><div><p className="seo-kicker">Si hay varios síntomas</p><h2 className="mt-4 font-display text-3xl font-bold md:text-5xl">La prioridad también forma parte del diagnóstico.</h2></div><div><p className="leading-7 text-slate-600">Cuando técnica, contenido y negocio se mezclan, un roadmap genérico solo aumenta el backlog. El método Ferova ordena hallazgos por impacto, esfuerzo, dependencia y riesgo.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link to="/metodo-ferova" className="seo-primary-button">Ver el método</Link><Link to="/contacto" className="inline-flex items-center justify-center rounded-lg border border-slate-300 px-6 py-3 font-semibold">Evaluar mi proyecto</Link></div></div></div></section>
  </main><Footer lang="es" /></div>;
}
