
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS title_en TEXT,
  ADD COLUMN IF NOT EXISTS excerpt_en TEXT,
  ADD COLUMN IF NOT EXISTS content_en TEXT,
  ADD COLUMN IF NOT EXISTS meta_title_en TEXT,
  ADD COLUMN IF NOT EXISTS meta_description_en TEXT,
  ADD COLUMN IF NOT EXISTS title_pt TEXT,
  ADD COLUMN IF NOT EXISTS excerpt_pt TEXT,
  ADD COLUMN IF NOT EXISTS content_pt TEXT,
  ADD COLUMN IF NOT EXISTS meta_title_pt TEXT,
  ADD COLUMN IF NOT EXISTS meta_description_pt TEXT;
